pantry = {
    "chicken": 500,
    "lemon": 2,
    "cumin": 24,
    "paprika": 18,
    "chilli powder": 7,
    "yogurt": 300,
    "oil": 450,
    "onion": 5,
    "garlic": 9,
    "ginger": 2,
    "tomato puree": 125,
    "almonds": 75,
    "rice": 500,
    "coriander": 20,
    "lime": 3,
    "pepper": 8,
    "egg": 6,
    "pizza": 2,
    "spam": 1,
}

recipes = {
    "Butter chicken": {
        "chicken": 750,
        "lemon": 1,
        "cumin": 1,
        "paprika": 1,
        "chilli powder": 2,
        "yogurt": 250,
        "oil": 50,
        "onion": 1,
        "garlic": 2,
        "ginger": 3,
        "tomato puree": 240,
        "almonds": 25,
        "rice": 360,
        "coriander": 1,
        "lime": 1,
    },
    "Chicken and chips": {
        "chicken": 100,
        "potatoes": 3,
        "salt": 1,
        "malt vinegar": 5,
    },
    "Pizza": {
        "pizza": 1,
    },
    "Egg sandwich": {
        "egg": 2,
        "bread": 80,
        "butter": 10,
    },
    "Beans on toast": {
        "beans": 1,
        "bread": 40,
    },
    "Spam a la tin": {
        "spam": 1,
        "tin opener": 1,
        "spoon": 1,
    },
    "Hamburger OA": {
        "pounds Certified Angus Beef ® ground beef, 80/20 lean" : 1-1/2,
        "cup mayonnaise" : 1-1/2,
        "tablespoon yellow mustard" : 1,
        "tablespoon grated yellow onion" : 1,
        "teaspoons hot sauce" : 2,
        "teaspoon Worcestershire sauce" : 1,
        "white hamburger buns" : 4,
        "tablespoons butter, room temperature" : 2,
        "teaspoons kosher salt" : 1-1/2,
        "teaspoon pepper" : 1/2,
        "slices American cheese" : 4,
        "cups shredded iceburg lettuce" : 2,
        "slices vine-ripe tomatoes" : 8,
    }
}
